name: Deploy docker image

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:

  build_docker_image:
    runs-on: ubuntu-18.04
    steps:

#     Build JAR
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests

#     Build Docker image
      - name: Build and tag image
        env:
          IMAGE_NAME: ${GITHUB_REPOSITORY}
        run: |
          echo "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:latest" .
          docker build -t "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:latest" .


      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      - name: Publish image
        env:
          IMAGE_NAME: $GITHUB_REPOSITORY
        run: echo "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:latest"


#     Publish image
#      - name: Publish to GPR
#        run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:latest"
